language: generic
env:
  global:
  - CODECOV_TOKEN="5c7759c2-a50f-44fd-84f4-b222b34693d0"
  - PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
  - NUMPY_VERSION=stable
  - MAIN_CMD='python setup.py'
  - CONDA_DEPENDENCIES='flake8 sphinx pyyaml coveralls coverage codecov pytest pytest-cov'
  - PIP_DEPENDENCIES=''
  - SETUP_XVFB=False
  - EVENT_TYPE='push pull_request'
  - SETUP_CMD='test'
  - CONDA_CHANNELS='conda-forge'
matrix:
  include:
  - env: PYTHON_VERSION=2.7
    os: linux
  - env: PYTHON_VERSION=2.7
    os: osx
  - env: PYTHON_VERSION=3.6
    os: linux
  - env: PYTHON_VERSION=3.6
    os: osx
  - env: PYTHON_VERSION=3.6
    os: windows
install:
- git clone --depth 1 git://github.com/astropy/ci-helpers.git
- source ci-helpers/travis/setup_conda.sh
- conda config --remove channels defaults
- conda install -y $CONDA_DEPENDENCIES
script:
- flake8 donfig
- pytest --cov=donfig donfig
after_success:
- if [[ $PYTHON_VERSION == 3.6 ]]; then coveralls; codecov; fi
deploy:
  - provider: pypi
    user: dhoese
    password:
      secure: uQgDeSGI0+uJmgYLVhM4QL1RsO13rwXxmLSiIPgJ9Wg7rv/tnTSlIyrp4EYrZun+sYzKOPNAcY4R81y9mN9y3DUzoPqF6kCmn7TYodPnvF+ehnUOOAMvz5I/wzMHqCr7x7S2ZGBWyo0tr0GxoCQDX17EYMpiKBlW+f8ww/KvrW0W+r9Hh6JhR82S7gP/mgLmcgZPm/Fvc7TU79cQjBb+Y+9wIoTi4pGOaefcWZNgUmdupVaqAZNG/9Q2nZGAtWQJr6x0LEmAqc2Q4RFRfTjOOO964nrk9WEyICA/UCKIR26jxZmrT1MSs8PSyhVSlZea/t47z5Spqx3SuHRE1sYCUK+N+mXg0NrFBT32IMvwebwUdOhWuDTR5hZmckCeJGBM5JlrW0bSr1782uceDToGGV/MRT+AgVZTxO2CMc9dzGzHf9dnXM+YoZjD4nDPUIqY47Y8c5gVM3UhtB32gBbCvGPIgmfMeV1hDdjowSnJrMUJjj8X5l3KxKo/goT0BeXX4J3PMfqzzaY9cKf9b0UXZo3u6lOZGvcqZTGOKP1hyyIC5KmIHiJvRvnMqFYv+QMunqJffj5RS1hsnzvI5bU3rzMtFZh+Lley5ZVcdvhtqKyb+K+HcmmfOmx9H6UaUkJ72CbBYFcXN7tJX9Lr6FtHF5TbWBqaxWt6z02ACLmGHkk=
    distributions: sdist
    skip_existing: true
    on:
      tags: true
      repo: pytroll/donfig
